Root create user
Proyecto-Final-psg/PF-Back pull request #3
Opened 2022-07-05 23:55 UTC by martinjbh

realice la ruta para crear usuario funciona tiene verificaciones bla bla....

2022-07-05 23:57 UTC, FlorenciaTaburelli approved these changes
muy bueno!!

2022-07-05 23:58 UTC, FlorenciaTaburelli approved these changes

2022-07-06 00:02 UTC, orimarselasirg requested changes
colocar una ruta get nueva

2022-07-06 00:03 UTC, martinjbh commented
todo listo

2022-07-06 00:04 UTC, orimarselasirg approved these changes
ok

2022-07-06 00:04 UTC, merged